name: blinker tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest, ubuntu-latest]
        cpp_compiler: [g++, clang++]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: macos-latest
            cpp_compiler: g++
          - os: ubuntu-latest
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Install Conan
      run: pip install conan

    - name: Configure Conan
      run: conan profile detect

    - name: Install Requirements
      working-directory: ./tests
      run: >
        conan install .
        --output-folder=./build
        --build=missing
        -s build_type=Debug

    - name: Configure CMake
      working-directory: ./tests
      run: >
        cmake -B build -S .
        -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
        -DCMAKE_BUILD_TYPE=Debug
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}

    - name: Build Tests
      working-directory: ./tests/build
      run: make

    - name: Run Tests
      working-directory: ./tests/build
      run: ctest --test-dir . --output-on-failure
